# Generated by Django 3.2.1 on 2021-05-07 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('wavLocation', models.FilePathField(default='D:\\An3\\Licenta\\automaticMusicTranscription\\backend\\source\\scores\\default.wav')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('scoreLocation', models.FilePathField(default='D:\\An3\\Licenta\\automaticMusicTranscription\\backend\\source\\scores\\default.pdf')),
                ('idWav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcriptor.audiorecording')),
            ],
        ),
    ]
